version: "3"
services:
  confi_db:
    image: postgres:11.2-alpine
    env_file:
     - .env-local-docker
    ports: 
      - "54321:5432"
  confi_app:
    build: .
    command: npm run start
    volumes:
      - .:/home/confi/
      - /home/confi/node_modules
    env_file:
     - .env-local-docker
    depends_on:
      - confi_db
    ports:
      - "3000:3000"
      - "9229:9229"
