version: "3"
services:
  confi_db:
    image: postgres:11.2-alpine
    env_file:
     - ./.env
    ports: 
      - "${DB_PORT}:5432"
  confi_app:
    build: .
    command: npm run start
    volumes:
      - .:/home/confi/
      - /home/confi/node_modules
    env_file:
     - ./.env
    depends_on:
      - confi_db
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "${APP_DEBUG_PORT}:${APP_DEBUG_PORT}"
